######### WARNING #########
# Logitech F710
# 1) Mode Select must be in D-Mode
# 2) MODE Light must be OFF
# If the Mode light is on, or if in X-Mode then the mapping is different

axis_linear:              # X/Y Translation - Left Stick
    x: 1
    y: 0
scale_linear:
    x: 1
    y: 1
scale_linear_turbo: 1.5

axis_angular: 2             # Yaw Rotation - Right Stick
scale_angular: 1.0

enable_button: 7            # Right Trigger = Deadman's Switch
# enable_turbo_button: 11     # Start Button


# AXES[]
#   0:ABS_X
#   1:ABS_Y
#   2:ABS_Z
#   3:ABS_RZ
#   4:ABS_HAT0X
#   5:ABS_HAT0Y

# BUTTONS[]
#   0:BTN_A
#   1:BTN_B
#   2:BTN_C
#   3:BTN_X
#   4:BTN_Y
#   5:BTN_Z
#   6:BTN_TL
#   7:BTN_TR
#   8:BTN_TL2
#   9:BTN_TR2
#   10:BTN_SELECT
#   11:BTN_START
